### ISSUE TITLE
Python version required

### ISSUE THREAD

**Issue by Douile** [nicolaskenner/python-fortnite-api-wrapper#1]
# I believe version is to high
You have required a very late version of python is this needed? It is preventing me from installing I believe you could set this as low as python 3 or possibly even 2

https://github.com/nicolaskenner/python-fortnite-api-wrapper/blob/7b6965a94ecdad1552140a60b5fa4ffa4f2ee447/setup.py#L20
https://github.com/nicolaskenner/python-fortnite-api-wrapper/blob/7b6965a94ecdad1552140a60b5fa4ffa4f2ee447/setup.py#L94

**Comment by nicolaskenner** [comment]
Resolved in https://github.com/nicolaskenner/python-fortnite-api-wrapper/commit/a333e6dc9a1d51a18718ce2b9fd3182d020625e9
