### ISSUE TITLE
timed out token ?

### ISSUE THREAD

**Issue by FeraruSilviuMarian** [nicolaskenner/python-fortnite-api-wrapper#12]
After a while, the stats retrieval doesn't work anymore, is it like a sort of login or something ?
I tried the async library but there's an exception thrown when trying to fetch the stats.
Any way to fix this problem ?

I was thinking maybe doing a time-based interval function, where I reinitialize the fortnite class every n seconds.

stats = fortnite.battle_royale_stats(username=username, platform=Platform.pc)

**Comment by nicolaskenner** [comment]
Tokens should automatically refresh before expiration. Feel free to reopen if you have more information on this.
