### ISSUE TITLE
launcher_token

### ISSUE THREAD

**Issue by mehranj73** [nicolaskenner/python-fortnite-api-wrapper#16]
I tried many times, fiddler doesn't give me the launcher_token. just account/api/oauth/exchange

**Comment by nicolaskenner** [comment]
A lot of people are having this issue. The solution as of right now seems to be using shared client tokens. See this answer on [qlaffont/fortnite-api](https://github.com/qlaffont/fortnite-api/issues/123#issuecomment-418782802).

**Comment by mehranj73** [comment]
Yes, I've already fixed issue with a shared token. Thank you
