### ISSUE TITLE
Unable to get token. Old token expired

### ISSUE THREAD

**Issue by Bluenix2** [nicolaskenner/python-fortnite-api-wrapper#20]
So my old token expired. And i can't get my new one. I was follwoing the tutorial without luck, it didnt work.

But then i made a huge discovery. It doesn't work with the new launcher. So when getting the token, make sure to have the beta **off**.

If you **don't** have the beta the settings tab should look like this: 
![image](https://user-images.githubusercontent.com/38372706/50521138-843d7a00-0ac4-11e9-9b66-409e8617d6a1.png)
If you **have** the beta the settings tab looks like this and you should click the button to go back: 
![image](https://user-images.githubusercontent.com/38372706/50521176-b2bb5500-0ac4-11e9-8075-93b7eb9741cc.png)

**Comment by Bluenix2** [comment]
For future reference

**Comment by byWambo** [comment]
The next Problem is, that there isn't the way to disable Beta now... So we need to find out, how to get the Fortnite Token.

**Comment by jolbol1** [comment]
Found a way to do this by sniffing the HTTP of and iPhone and launching the fortnite app instead!

**Comment by Bluenix2** [comment]
So it isn't possible on the PC anymore then?

**Comment by byWambo** [comment]
So People. Every Fortnite Token and Client Token is the same. So please take the Tokens from the readme.md and your good to go. I hope @nicolaskenner closes this Issue
